// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package general

import (
	"time"
)

type UUser struct {
	ID           int64      `json:"id"`
	Username     string     `json:"username"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}
